name: Main CI

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-all:
    name: Test
    if: ${{ !startsWith(github.event.head_commit.message, 'release:') }}
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup toolchain
        uses: ./.github/actions/setup-toolchain

      - name: Run CI checks
        run: moon ci :format :lint :testci :typecheck
